sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- '6'
before_script:
- npm prune
script:
- npm run report:test
- npm run build
after_success:
- npm run report:coverage
- "echo 'installing FCM dependencies'"
- pwd && ls
- cd ./functions && npm install && cd ../
- "echo 'FCM dependencies installed'"
- firebase deploy --token=${FIREBASE_TOKEN}
- "open 'poll-app-67a23.firebaseapp.com'"
