sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- '6'
before_script:
- npm prune
script:
- npm run report:test
- npm run build
- npm run deploy
after_success:
- npm run report:coverage
- firebase deploy --token=${FIREBASE_TOKEN}
