
sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
# test & report
  - npm run test && npm run report:js
#  - npm run report:performance 
  - npm run report:js
# check coverage
# build
  - npm run build
# deploy
after_success:
  - npm run deploy
# send coverage report
# release/publish
# open