
sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
#  - npm prune
script:
#  - npm run cover
#  - npm run check-coverage
#  - npm run build
after_success:
#  - npm run report-coverage:codecov
#  - npm run report-coverage:codacy
#  - npm run semantic-release