
sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
# test & report
  - npm run report:test
#  - npm run report:performance 
#  - npm run report:js
# check coverage
# build
  - npm run build
# deploy
  - npm run deploy
after_success:
# send coverage report
  - npm run report:coverage
# release/publish