FROM node:8.1.4-alpine

WORKDIR /www

# deps for node-sass
RUN apk --update add --no-cache \
      make \
      gcc \
      g++ \
      python2 \
 && rm -rf /var/cache/apk/*

COPY package.json ./
RUN npm install